{
 "title": "IOT Cars",
 "tags": [ "sandbox" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Request State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_request_state{CURRENT_STATE!=\"DEPARTED\"}",
     "legendFormat": "{{CURRENT_STATE}}"
    }
   ]
  },
  {
   "title": "Current Parameter Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "voltdbbl_parameter_name", "legendFormat": "{{PARAM_NAME}}" }
   ]
  },
  {
   "title": "IOT Events Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"GetOptions\"}[1m]) > 0)",
     "legendFormat": "Check for parking spaces"
    },
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"iotcarsprocs.SelectOption\"}[1m]) > 0)",
     "legendFormat": "Book  a parking space"
    },
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"stop_charge_session\"}[1m]) > 0)",
     "legendFormat": "Stop Charging"
    },
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"end_charge_session\"}[1m]) > 0)",
     "legendFormat": "Leave Charger"
    },
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"start_charge_session\"}[1m]) > 0)",
     "legendFormat": "Start Charging"
    }
   ]
  },
  {
   "title": "Charger State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltdbbl_charger_state", "legendFormat": "{{CURRENT_STATE}}" }
   ]
  },
  {
   "title": "Revenue from area 94597 per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "voltdbbl_activity_in_area", "legendFormat": "{{FEE_TYPE}}, US$" }
   ]
  },
  {
   "title": "Parameters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "voltdbbl_parameter_name", "legendFormat": "{{PARAM_NAME}}" }
   ]
  },
  {
   "title": "Availability 'n' minutes from now",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_charger_availability_in",
     "legendFormat": "{{MINS}}"
    }
   ]
  }
 ]
}